FROM rocm/pytorch:rocm5.0.1_ubuntu18.04_py3.7_pytorch_1.9.0
LABEL github="https://github.com/CBICA/GaNDLF"
LABEL docs="https://cbica.github.io/GaNDLF/"
LABEL version=1.0
# The base image contains ROCm, python 3.7 and pytorch already, no need to install those
COPY . /GaNDLF
WORKDIR /GaNDLF
RUN pip install -e .
# Entrypoint forces all commands given via "docker run" to go through python, CMD forces the default entrypoint script argument to be gandlf_run
# If a user calls "docker run gandlf:[tag] gandlf_anonymize", it will resolve to running "python gandlf_anonymize" instead.
# CMD is inherently overridden by args to "docker run", entrypoint is constant.
ENTRYPOINT python
CMD gandlf_run