#!usr/bin/env python
# -*- coding: utf-8 -*-

import os, argparse

from GANDLF.cli import copyrightMessage


# main function
if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        prog="GANDLF_VerifyInstall",
        formatter_class=argparse.RawTextHelpFormatter,
        description="Verify GaNDLF installation.\n\n" + copyrightMessage,
    )

    try:
        import GANDLF as gf

        print("GaNDLF installed version:", gf.__version__)
    except:
        raise Exception(
            "GaNDLF not properly installed, please see https://mlcommons.github.io/GaNDLF/setup"
        )

    # we always want to do submodule update to ensure any hash updates are ingested correctly
    try:
        os.system("git submodule update --init --recursive")
    except:
        print("Git was not found, please try again.")
    os.system("pip install -e .")

    args = parser.parse_args()

    print("GaNDLF is ready. See https://mlcommons.github.io/GaNDLF/usage")
