#!usr/bin/env python
# -*- coding: utf-8 -*-
import platform

from GANDLF.utils import get_git_hash


if __name__ == "__main__":
    print(f"Git hash: {get_git_hash()}")
    print(f"Platform: {platform.platform()}")
    print(f"Machine: {platform.machine()}")
    print(f"Processor: {platform.processor()}")
    print(f"Architecture: {platform.architecture()}")
    print(f"Python version: {platform.python_version()}")
    print(f"Python implementation: {platform.python_implementation()}")
    print(f"Python compiler: {platform.python_compiler()}")
    print(f"Python build: {(' ').join(list(platform.python_build()))}")
