#!usr/bin/env python
# -*- coding: utf-8 -*-

import os, argparse
from datetime import date
from GANDLF.cli.patch_extraction import patch_extraction
from GANDLF.utils import *

fix_paths(os.getcwd())  # add relevant vips path


if __name__ == "__main__":
    copyrightMessage = (
        "Contact: software@cbica.upenn.edu\n\n"
        + "This program is NOT FDA/CE approved and NOT intended for clinical use.\nCopyright (c) "
        + str(date.today().year)
        + " University of Pennsylvania. All rights reserved."
    )

    parser = argparse.ArgumentParser(
        prog="GANDLF_PatchMiner",
        formatter_class=argparse.RawTextHelpFormatter,
        description="Construct patches from whole slide image(s).\n\n"
        + copyrightMessage,
    )

    parser.add_argument(
        "-i",
        "--input_CSV",
        dest="input_path",
        help="input path for the tissue",
        required=True,
    )
    parser.add_argument(
        "-o",
        "--output_path",
        dest="output_path",
        default=None,
        required=True,
        help="output path for the patches",
    )
    parser.add_argument(
        "-c",
        "--config",
        type=str,
        dest="config",
        help="config (in YAML) for running OPM. Needs 'scale' and 'patch_size' to be defined, otherwise defaults to 16 and (256, 256), respectively.",
        required=False,
    )

    args = parser.parse_args()

    patch_extraction(args)

    print("Finished.")
