#! /bin/bash
# this file is used to run gpu jobs on the cluster in a proper manner so 
# that the CUDA_VISIBLE_DEVICES environment variable is properly initialized
# ref: https://sbia-wiki.uphs.upenn.edu/wiki/index.php/GPU_Computing#Directing_Jobs_to_a_Specific_GPU_with_the_get_CUDA_VISIBLE_DEVICES_Utility

# get free cuda device
CUDA_VISIBLE_DEVICES=`get_CUDA_VISIBLE_DEVICES` || exit
export CUDA_VISIBLE_DEVICES

# # using multiple GPUs
# CUDA_VISIBLE_DEVICES=`get_CUDA_VISIBLE_DEVICES 2` || exit
# export CUDA_VISIBLE_DEVICES

# run the command given to the shell verbatim
$*
